name: Elixir CI

on:
  pull_request:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-20.04

    env:
      MIX_ENV: test
      ImageOS: ubuntu20

    steps:
    - uses: actions/checkout@v3
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.15.x' # Define the elixir version [required]
        otp-version: '26' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v3
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: |
        sudo apt-get install -y erlang-dev libsdl2-dev libsdl2-image-dev
        mix local.hex --force
        mix local.rebar --force
        mix deps.get --only test
    - run: mix compile
    - name: Run tests
      run: mix test
